---
name: Dr Arran Hamlet
date: "`r format(Sys.time(), '%B, %Y')`"
position: Epidemic Intelligence Service Officer
address: "Centers for Disease Control and Prevention, Atlanta, USA"
aboutme: "Infectious disease epidemiologist and mathematical modeller with extensive experience in data analysis and statistical/mechanistic modelling to inform outbreak response and public health policy."
email: arranh92@gmail.com
github: arranhamlet
linkedin: arranhamlet
orcid: 0000-0003-0871-0640
output: 
  vitae::awesomecv:
    keep_tex: true
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tidyverse)
library(scholar)
```

# Education

```{r education}
tribble(
  ~ degree, ~ uni, ~ loc, ~ dates, ~ details,
  "PhD titled 'Yellow fever in South America: The role of environment and host on transmission dynamics'", "Imperial College London", "London, United Kingdom", "Jan 2017-Jan 2020", "Looked at understanding the epidemiology of yellow fever across South America, with a focus on Brazil, examining the roles of climate, environment and host. Employed a variety of statistical and mechanistic modelling techniques. Worked with the WHO, the Brazilian Ministry of Health and the university Fundação Oswaldo Cruz.",

  "MSc in Epidemiology", "Imperial College London", "London, United Kingdom", "Oct 2014-Oct 2015", "Awarded a distinction for my dissertation project titled 'The Seasonality of Yellow Fever in Africa.'",
  
  "BSc in Biology with Psychology", "Queen Mary University of London", "London, United Kingdom", "Sep 2011-May 2014", "Focus on Evolutionary Biology and Neuroscience."
) %>% 
  detailed_entries(uni, loc, degree, dates, details)
```

# Employment
```{r employment}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, ~ details,
  "Epidemic Intelligence Service Officer (Washington State Department of Health)", "Centers for Disease Control and Prevention", "Seattle, USA", "July 2022-", "\\textbf{Select projects below.}\\\\",

  "Epidemic Intelligence Service Officer (Washington State Department of Health)", "Centers for Disease Control and Prevention", "Seattle, USA", "July 2022-",      
    "\\textbf{Lead on an Epi-Aid investigating the rise in detections of Corynebacterium diphtheriae in Washington state}.",

"Epidemic Intelligence Service Officer (Washington State Department of Health)", "Centers for Disease Control and Prevention", "Seattle, USA", "July 2022-",      
    "\\Lead on estimating the prevalence of long COVID in Washington using a mathematical model to estimate age, sex, race-ethnicity, and county level prevalence of long COVID over time",

"Epidemic Intelligence Service Officer (Washington State Department of Health)", "Centers for Disease Control and Prevention", "Seattle, USA", "July 2022-",
"\\Lead on an outbreak investigation of gastrointestinal illness on the Pacific Crest Trail}.
    \\\\ - Lead the outbreak investigation and response. This included, survey design, patient interviews, epidemiological analysis and environmental sampling of pit latrines and shared use facilities.",

"Epidemic Intelligence Service Officer (Washington State Department of Health)", "Centers for Disease Control and Prevention", "Seattle, USA", "July 2022-", 
"\\Evaluation of the rabies surveillance system, comparing existing rabies mandatory reporting with syndromic surveillance collected from emergency departments and urgent care centers.") %>% 
  detailed_entries(company, loc, role, dates, details, .protect = F)
```

```{r employment1_5}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, ~ details,
"", "", "", "",
"\\Part of the WA DOH team, supervising and responding to Tuberculosis in the WA correctional system following the largest outbreak in decades. Provided leadership and analytical support..",
"", "", "", "",
"\\Working on various projects with the CDC malaria group and the Presidents Malaria Initiative.",

"Visiting Researcher", "Imperial College London", "London, United Kingdom", "Jun 2022-", "Visiting researcher for mathematical and statistical modelling of malaria and yellow fever.",

"Postdoctoral Researcher (Malaria)", "Imperial College London", "London, United Kingdom", "Jan 2020-Jun 2022", "Involved in a variety of projects assessing the public health impact of various control measures on the burden of malaria across Africa using mechanistic transmission models.",

"Postdoctoral Researcher (Malaria)", "Imperial College London", "London, United Kingdom", "Jan 2020-Jun 2022", "Lead researcher on a piece of work assessing the potential impact of Anopheles stephensi establishment on malaria transmission in Ethiopia.",

"Postdoctoral Researcher (Nigeria COVID-19 response)", "Imperial College London", "London, United Kingdom", "Apr 2020-Dec 2020", "Lead researcher for Imperial College London's data analytics and modelling support for the Nigerian Government.",

"Postdoctoral Researcher (COVID-19 response)", "Imperial College London", "London, United Kingdom", "Feb 2020-Dec 2020", "Seconded through the Global Outbreak Alert and Response Network to provide analytical support for the WHO in Geneva Feb - Apr 2020 to understand the initial spread of COVID-19.",

"PhD in Infectious Disease Modelling", "Imperial College London", "London, United Kingdom", "Jan 2017 - Jan 2020", "PhD thesis titled 'Yellow fever in South America: The role of environment and host on transmission dynamics'.",
"PhD in Infectious Disease Modelling", "Imperial College London", "London, United Kingdom", "Jan 2017 - Jan 2020", "Explored the role of climate, landcover and zoonotic reservoirs on the distribution of yellow fever in South America. Additional work focussed on estimating the vaccination coverage of yellow fever globally over time.",

"Research Assistant", "Imperial College London", "London, United Kingdom", "Oct 2015 - Dec 2016", "Outbreak analysis and response for the 2015-2016 outbreak in Angola and the Democratic Republic of the Congo working with the World Health Organization (WHO).",

"Research Assistant", "Imperial College London", "London, United Kingdom", "Oct 2015 - Dec 2016", "Responsible for estimating population-level vaccination coverage across Africa and the development of an open-source tool to explore this information."

) %>% 
  detailed_entries(company, loc, role, dates, details, .protect = F)
```
\newpage
# Consultancy
```{r consultancy}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, ~ details,
  "Course Instructor and Curriculum Designer", "AppliedEpi", "Online", "Jan 2022 - ", "AppliedEpi is the non-profit behind the Epidemiologist R Handbook, used by almost 2 million epidemiologists worldwide. Since early 2022 they have offered courses teaching applied R coding to epidemiologists, running over a hundred courses for dozens of Ministries of Health globally as well as the WHO, CDC and various other institutions.",
    "Course Instructor and Curriculum Designer", "AppliedEpi", "Online", "Jan 2022 - ", "Designed and created numerous modules and the Advanced Statistics in R course.",
      "Course Instructor and Curriculum Designer", "AppliedEpi", "Online", "Jan 2022 - ", "I have lead or demonstrated on courses for almost a dozen agencies, including the Health Departments for Michigan, Wales, Canada, Camobdia, Kazakhstan.",
      "Course Instructor and Curriculum Designer", "AppliedEpi", "Online", "Jan 2022 - ", "Currently lead author responsible for a team of epidemiologists writing chapters of data analysis and regression in a field manual for applied epidemiologists.",

  "Epidemiologist: COVID-19", "World Health Organization", "Geneva, Switzerland", "Feb 2020 - Apr 2020", "Provided technical support for the WHO in the Health Emergency Information and Risk Assessment (HIM) pillar through GOARN deployment",
  "Epidemiologist: Yellow fever", "World Health Organization", "Geneva, Switzerland", "Jul 2016 - Sep 2016", "Commissioned to produce a report evaluating the risk of outbreaks of yellow fever across Africa as a result of ongoing transmission in Angola and the Democratic Republic of the Congo and the potential for introduction into Asia.",
  "Epidemiologist", "Ozygen Systems", "London, United Kingdom", "Feb 2016 - Mar 2016", "Hired to produce a report on numerous pathogens involved in nosocomial infection and to evaluate the applicability of ozone decontamination technology in UK healthcare settings to limit their spread."
) %>% 
  detailed_entries(company, loc, role, dates, details)
```

# Funding awards
```{r awards}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, ~ details,
   "Course Instructor and Curriculum Designer", "AppliedEpi", "Online", "Jan 2022 - ", "Curriculum designer and creator, lecturer for courses teaching epidemiologists applied R coding.",

  "MRC Pump Priming (£23,000)", "Imperial College London", "London, United Kingdom", "Nov 2019", "Jointly awarded £23,000 with co-PI Natsuko Imai to run a week long training workshop in Rio de Janeiro focusing on the use of mathematical models in outbreak response and policy.",

  "MRC Exceptional Training Opportunity", "Imperial College London", "London, United Kingdom", "Oct 2017/Aug 2018/Jun 2019", "Oct 2017: Awarded £4600 in several different awards to present results to the WHO, PAHO and the Brazilian Ministry of Health travel, as well as to help run a workshop on an introduction to ifnectious disease modelling at a university in Bogota, Colombia."

) %>% 
  detailed_entries(company, loc, role, dates, details)
```

# Teaching
```{r teaching}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, ~ details,
  
  "Shortcourse co-organiser", "Imperial College London", "London, United Kingdom", "Jan 2021 - Sep 2021", "Co-organiser on the departments 'Mathematical modelling for the control of infectious diseases' short course, run since 1990 and designed to teach pubic health professionals about infectious disease modelling.",
  "Shortcourse co-organiser", "Imperial College London", "London, United Kingdom", "Jan 2021 - Sep 2021", "Responsible for helping redesign, and restructure, the course in order to deliver it fully online in light of the ongoing COVID-19 pandemic.",
  
  "PhD Assessor", "University of São Paulo", "São Paulo, Brazil", "Oct 2020-Jun 2023", "Examining progress and assisting with the research of a PhD student's project titled 'Spatio-temporal dynamics of yellow fever in Brazil'.",
  
  "MSc Dissertation Supervisor", "Imperial College London", "London, United Kingdom", "May 2020 - Oct 2020", "Designed and supervised MSc Epidemiology projects looking at the effect of forest fragmentation on yellow fever in Southern Brazil, and exploring the differences in transmission dynamics between yellow fever, dengue and zika.",
  
  "Graduate Teaching Assistant", "Imperial College London", "London, United Kingdom", "Jan 2017 - Jun 2022", "Teaching assistant and demonstrator for numerous modules on infectious disease modelling, statistical analysis and epidemiology.",
  
  "Shortcourse Demonstrator", "Imperial College London", "Bogota, Colombia", "Jun 2019", "Demonstrator and lecturer on a course coordinated between Imperial College London, Instituto Nacional De Salud and Pontificia Universidad Javeriana Bogota which aimed to give an introduction to infectious disease modelling.",
  
  "Shortcourse Demonstrator", "Imperial College London", "London, United Kingdom", "Sep 2017/Sep 2018/Sep 2019", "Demonstrator on numerous practical exercises and lectures on data analysis and infectious disease modelling on the aformentioned departments 'Mathematical modelling for the control of infectious diseases' short course.",
  
  "Design and implementation of an online platform for teaching infectious disease modelling", "Imperial College London", "London, United Kingdom", "Jan 2019 - Sept 2019", "Responsible for liasing between programming team and course organisers to design and translate existing work. Highly successful implementation led to the platform being adopted for use in future shorecourses and the MSc Epidemiology at Imperial College London"
  
) %>% 
  detailed_entries(company, loc, role, dates, details)
```
  
# Presentations
```{r presentations}
tribble(
  ~ role, ~ company, ~ loc, ~ dates,
  
  "Estimating the Burden and Distribution of Long COVID in Washington State", "Western States Modeling Symposium", "Virtual", "Sep 2023",
  
      "Gastrointestinal illness among hikers on the Washington State Pacific Crest Trail, August–October 2022.", "EIS Conference 2023 and CSTE 2023", "USA", "Apr 2023",
  
    "The potential public health consequences of COVID-19 on malaria in Africa", "London Malaria Network", "London, United Kingdom", "Oct 2020",
  
    "Seasonality of agricultural exposure more important than seasonality of climate for predicting yellow fever transmission in Brazil", "American Society of Tropical Medicine and Hygiene", "National Harbor, USA", "Nov 2019",
  
    "Statistical and mathematical modelling of yellow fever in South America", "Outbreak Analysis and Modelling for Public Health", "Bogota, Colombia", "Jun 2019",

  "Land-use,  vegetation  and  habitat fragmentation  as  drivers  of  yellow  fever  transmission  in  South America", "International Conference on One Medicine One Science", "Chiang Mai, Thailand", "Feb 2019",
  
  "Yellow fever in Brazil - Modelling as a tool to inform outbreak response and public health policy", "Yellow fever forecasting: Embedding   modelling in lessons learnt exercises", "Brasilia, Brazil", "Nov 2018"
  
) %>% 
  detailed_entries(company, loc, role, dates)
```

# Publications
```{r publications_load, echo = FALSE, message = FALSE, warning = FALSE, results = FALSE}
pubs <- scholar::get_publications("xk9BhHUAAAAJ")%>%
  dplyr::mutate(author = author %>%
                  as.character,
                journal = journal %>%
                  replace(journal %in% "bioRxiv", "BioRxiv") %>%
                  replace(journal %in% "medRxiv", "MedRxiv"),
                first_author = case_when(stringr::str_starts(author, "A Hamlet|ATP Hamlet") ~ TRUE,
                                         TRUE ~ FALSE),
                preprint = case_when(journal %in% c("bioRxiv", "BioRxiv", "MedRxiv", "medRxiv", "") ~ TRUE,
                                     TRUE ~ FALSE),
                report = case_when(stringr::str_starts(title, "Report") ~ TRUE,
                                   TRUE ~ FALSE)) %>%
  dplyr::arrange(desc(year), desc(cites))

# pubs <- pubs[-which(pubs$cites == 0 & pubs$year < 2021), ]
if(any(duplicated(pubs$title))) pubs <- pubs[-which(duplicated(pubs$title)), ]
pubs <- pubs[!is.na(pubs$year), ]

#Fix journal names
pubs <- pubs %>%
  mutate(
    journal = str_to_title(journal),
    journal = gsub("Plos", "PLoS", journal),
    journal = gsub("Bmc", "BMC", journal),
    journal = case_when(
    journal == "Bmj" ~ "BMJ",
    TRUE ~ journal
  )) %>% filter(!grepl("vol 6, pg e100|Imperial College", title)) %>%
   dplyr::filter(!journal %in% c("doi. org/",
                                "Impact of non-pharmaceutical interventions (NPIs) to reduce COVID",
                                "Imperial College COVID",
                                "Imperial College London",
                                "Imp\\. Coll. COVID-",
                                "Imperial College COVID-") & report == F & preprint == F & journal != "Imperial College London") %>% filter(!grepl("Correction", title)) %>%
   dplyr::arrange(desc(year), desc(cites)) %>%
  
    rowwise() %>%
  mutate(
    author = gsub("A Hamlet|ATP Hamlet", "\\\\textcolor{red}{\\\\textbf{A Hamlet}} ", author)
  )

```

## First author publications - `r pubs %>% dplyr::filter(first_author == T & preprint == F) %>% nrow()`
## Additional publications - `r pubs %>% dplyr::filter(first_author == F & preprint == F) %>% nrow()`
