---
name: Dr Arran Hamlet
date: "`r format(Sys.time(), '%B, %Y')`"
position: Epidemic Intelligence Service Officer
address: "Centers for Disease Control and Prevention, Atlanta, USA"
aboutme: "Infectious disease epidemiologist and mathematical modeller with extensive experience in data analysis and statistical/mechanistic modelling to inform outbreak response and public health policy."
email: arranh92@gmail.com
github: arranhamlet
linkedin: arranhamlet
output: 
  vitae::awesomecv:
    keep_tex: true
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tidyverse)
library(scholar)
```

# Education

```{r education}
tribble(
  ~ degree, ~ uni, ~ loc, ~ dates, ~ details,
  "PhD titled 'Yellow fever in South America: The role of environment and host on transmission dynamics'", "Imperial College London", "London, United Kingdom", "Jan 2017-Jan 2020", "Looked at understanding the epidemiology of yellow fever across South America, with a focus on Brazil, examining the roles of climate, environment and host. Employed a variety of statistical and mechanistic modelling techniques. Worked with the WHO, the Brazilian Ministry of Health and the university Fundação Oswaldo Cruz.",

  "PhD titled 'Yellow fever in South America: The role of environment and host on transmission dynamics'", "Imperial College London", "London, United Kingdom", "Jan 2017-Jan 2020", "Supervised by Dr Tini Garske and Professor Neil Ferguson, fully funded by the UK Medical Research Council.",
  
  "MSc in Epidemiology", "Imperial College London", "London, United Kingdom", "Oct 2014-Oct 2015", "Awarded a distinction for my dissertation project titled 'The Seasonality of Yellow Fever in Africa.'",
  
  "BSc in Biology with Psychology", "Queen Mary University of London", "London, United Kingdom", "Sep 2011-May 2014", "Focus on Evolutionary Biology and Neuroscience."
) %>% 
  detailed_entries(uni, loc, degree, dates, details)
```

# Employment
```{r employment}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, ~ details,
  "Epidemic Intelligence Service Officer (Washington State Department of Health)", "Centers for Disease Control and Prevention", "Seattle, USA", "July 2022-", "\\textbf{Select projects below.}\\\\",

  "Epidemic Intelligence Service Officer (Washington State Department of Health)", "Centers for Disease Control and Prevention", "Seattle, USA", "July 2022-",      
    "\\textbf{Lead on an Epi-Aid investigating the rise in detections of Corynebacterium diphtheriae in Washington state}.
    \\\\ - Co-lead of a multidisciplinary team from local, state and federal agencies, tasked with investigating the increase in C. diphtheriae detections in Washington State, 2018-2023. 
    \\\\ - Organized meetings and coordination with local health jurisdictions and hospital system partners to gain access to medical records for chart abstraction, and to understand the context of the increases.
    \\\\ - Conducted interviews with laboratory directors to understand changes in testing practices, and with partners providing housing and medical care to those experiencing homelessness.
    \\\\ - Analysis currently ongoing, focusing on changes in transmission and surveillance, the clinical course and social factors related to the increase in detections.",

"Epidemic Intelligence Service Officer (Washington State Department of Health)", "Centers for Disease Control and Prevention", "Seattle, USA", "July 2022-",      
    "\\textbf{Lead on estimating the prevalence of long COVID in Washington}.
    \\\\ - Created a mathematical model using WA DOH data to estimate age, sex, race-ethnicity, and county level prevalence of long COVID over time. 
    \\\\ - The method was designed and validated with subject matter experts from WA DOH and the CDC to produce a highly flexible approach that integrated existing data sources with the latest findings from scientific literature.
    \\\\ - Results presented to CSTE, WA DOH leadership, and used in discussions with the Washington State Senate for long COVID advocacy and the positioning of resources.
    \\\\ - Manuscript under review and the approach is highlighted in a CSTE position paper.",

"Epidemic Intelligence Service Officer (Washington State Department of Health)", "Centers for Disease Control and Prevention", "Seattle, USA", "July 2022-",
"\\textbf{Lead on an outbreak investigation of gastrointestinal illness on the Pacific Crest Trail}.
    \\\\ - Lead the outbreak investigation and response. This included, survey design, patient interviews, epidemiological analysis and environmental sampling of pit latrines and shared use facilities.
    \\\\ - The findings led to changes in WA DOH policy on the use of social media in outbreak investigation, a MMWR article was published and presentations given at EIS and CSTE conferences.",

"Epidemic Intelligence Service Officer (Washington State Department of Health)", "Centers for Disease Control and Prevention", "Seattle, USA", "July 2022-", 
"\\textbf{Evaluation of the rabies surveillance system}.
    \\\\ - Compared existing rabies mandatory reporting with syndromic surveillance collected from emergency departments and urgent care centers on potential rabies exposures, and with recorded post-exposure prophylaxis. 
    \\\\ - Identified clear gaps in certain counties reporting of rabies, with some of these reporting less than 1 in 10 estimated rabies exposures.
    \\\\ - Currently assessing whether we can use these alternative data systems to capture a more accurate understanding of human-rabies encounters, and remove potential rabies exposure as a notifiable condition.") %>% 
  detailed_entries(company, loc, role, dates, details, .protect = F)
```

```{r employment1_5}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, ~ details,
"", "", "", "",
"\\textbf{Tuberculosis in the correctional system.}.
    \\\\ - Part of the WA DOH team, supervising and responding to Tuberculosis in the WA correctional system following the largest outbreak in decades. Provided leadership and analytical support.",
"", "", "", "",
"\\textbf{Malaria in Uganda and Ethiopia}.
    \\\\ - Working with the CDC malaria group to analyse a study looking at increasing funding to community healthcare workers during 2021-2022, results currently being written up for a manuscript.
    \\\\ - Working with the Presidents Malaria Initiative and PATH to provide subnational estimates of the impact of Anopheles stephensi on malaria transmission in Ethiopia.",

"Visiting Researcher", "Imperial College London", "London, United Kingdom", "Jun 2022-", "Visiting researcher for mathematical and statistical modelling of malaria and yellow fever.",
"Visiting Researcher", "Imperial College London", "London, United Kingdom", "Jun 2022-", "Provide direction and feedback for projects, reviewing manuscripts and planning strategic research goals.",

"Postdoctoral Researcher (Malaria)", "Imperial College London", "London, United Kingdom", "Jan 2020-Jun 2022", "Involved in a variety of projects assessing the public health impact of various control measures on the burden of malaria across Africa using mechanistic transmission models.
\\\\ - Several of these outputs were used by organizations such as the WHO, IVCC, MedAccess and Ministries of Health to understand the potential benefits of different malaria control strategies and the utility of next generation bednets such as Piperonyl butoxide (PBO) or Interceptor® G2 in areas of high insecticide resistance.",

"Postdoctoral Researcher (Malaria)", "Imperial College London", "London, United Kingdom", "Jan 2020-Jun 2022", "Assessed the impact of disruption caused by the SARS-CoV-2 pandemic on malaria control across Africa. Results published Nature Medicine as joint first author.",

"Postdoctoral Researcher (Malaria)", "Imperial College London", "London, United Kingdom", "Jan 2020-Jun 2022", "Lead researcher on a piece of work assessing the potential impact of Anopheles stephensi establishment on malaria transmission in Ethiopia.
\\\\ - This piece of work was conducted with Abt Associates and the Presidents Malaria Initiative.
\\\\ - The findings were published in BMC Medicine, and have been widely cited by the WHO and PMI in their advocacy work.",

"Postdoctoral Researcher (Nigeria COVID-19 response)", "Imperial College London", "London, United Kingdom", "Apr 2020-Dec 2020", "Lead researcher for Imperial College London's data analytics and modelling support for the Nigerian Government.",
"Postdoctoral Researcher (Nigeria COVID-19 response)", "Imperial College London", "London, United Kingdom", "Apr 2020-Dec 2020", "Conducted rapid analysis to answer specific questions in order to provide evidence for policy decisions to be made by the Nigerian Presidential Task Force.",
"Postdoctoral Researcher (Nigeria COVID-19 response)", "Imperial College London", "London, United Kingdom", "Apr 2020-Dec 2020", "Produced a multitidue of reports as well as regular state-specicic analysis that fed into NCDC, US CDC and UK Department for International Development decision making.",
"Postdoctoral Researcher (Nigeria COVID-19 response)", "Imperial College London", "London, United Kingdom", "Apr 2020-Dec 2020", "A number of position papers can be found at https://statehouse.gov.ng/covid19/2020/09/18/evidence-based-guidance-on-measures-to-curb-the-spread-of-covid-19/.",

"Postdoctoral Researcher (COVID-19 response)", "Imperial College London", "London, United Kingdom", "Feb 2020-Dec 2020", "Provided technical support and input for numerous reports and projects, with a focus on work in Low-to-Middle-Income Countries (LMIC) and on quantifying the underascertainment of mortality. Work contributed to several peer reviewed papers and numerous position papers.",

"Postdoctoral Researcher (COVID-19 response)", "Imperial College London", "London, United Kingdom", "Feb 2020-Dec 2020", "Seconded through the Global Outbreak Alert and Response Network to provide analytical support for the WHO in Geneva Feb - Apr 2020 to understand the initial spread of COVID-19.",

"PhD in Infectious Disease Modelling", "Imperial College London", "London, United Kingdom", "Jan 2017 - Jan 2020", "PhD thesis titled 'Yellow fever in South America: The role of environment and host on transmission dynamics'.",
"PhD in Infectious Disease Modelling", "Imperial College London", "London, United Kingdom", "Jan 2017 - Jan 2020", "Explored the role of climate, landcover and zoonotic reservoirs on the distribution of yellow fever in South America. Additional work focussed on estimating the vaccination coverage of yellow fever globally over time.",

"Research Assistant", "Imperial College London", "London, United Kingdom", "Oct 2015 - Dec 2016", "Outbreak analysis and response for the 2015-2016 outbreak in Angola and the Democratic Republic of the Congo working with the World Health Organization (WHO).\\\\ - This involved rapid modelling and data analytics to answer questions on the spread and suitability of the environment for transmission, and planning vaccination campaign strategies to stop the outbreak.\\\\ - Hired as a consultant to produce a report on strategies for optimally reducing the risk of yellow fever transmission in Africa, and the potential for global spread.",
"Research Assistant", "Imperial College London", "London, United Kingdom", "Oct 2015 - Dec 2016", "Responsible for estimating population-level vaccination coverage across Africa and the development of an open-source tool to explore this information. Currently utilised by researchers and the WHO."

) %>% 
  detailed_entries(company, loc, role, dates, details, .protect = F)
```
\newpage
# Consultancy
```{r consultancy}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, ~ details,
  "Course Instructor and Curriculum Designer", "AppliedEpi", "Online", "Jan 2022 - ", "AppliedEpi is the non-profit behind the Epidemiologist R Handbook, used by almost 2 million epidemiologists worldwide. Since early 2022 they have offered courses teaching applied R coding to epidemiologists, running over a hundred courses for dozens of Ministries of Health globally as well as the WHO, CDC and various other institutions.",
    "Course Instructor and Curriculum Designer", "AppliedEpi", "Online", "Jan 2022 - ", "I was responsible for designing and creating several of the modules on data management and analysis, as well as the sole designer and creator of the Advanced Statistics in R course.",
      "Course Instructor and Curriculum Designer", "AppliedEpi", "Online", "Jan 2022 - ", "I have lead or demonstrated on courses for almost a dozen agencies, including the Health Departments for Michigan, Wales, Canada, Camobdia, Kazakhstan.",
      "Course Instructor and Curriculum Designer", "AppliedEpi", "Online", "Jan 2022 - ", "Currently lead author responsible for a team of epidemiologists writing chapters of data analysis and regression in a field manual for applied epidemiologists.",

  "Epidemiologist: COVID-19", "World Health Organization", "Geneva, Switzerland", "Feb 2020 - Apr 2020", "Provided technical support for the WHO in the Health Emergency Information and Risk Assessment (HIM) pillar through GOARN deployment",
  "Epidemiologist: COVID-19", "World Health Organization", "Geneva, Switzerland", "Feb 2020 - Apr 2020", "Work involved exploring and quantifying mortality, transmission and country specific impacts through data analysis and visualisation in real time as the COVID-19 pandemic unfolded. Aspects of data visualisation acknowledged in https://worldhealthorg.shinyapps.io/covid/.",
  "Epidemiologist: COVID-19", "World Health Organization", "Geneva, Switzerland", "Feb 2020 - Apr 2020", "Continued to provide adhoc support till Dec 2020.",
  "Epidemiologist: Yellow fever", "World Health Organization", "Geneva, Switzerland", "Jul 2016 - Sep 2016", "Commissioned to produce a report evaluating the risk of outbreaks of yellow fever across Africa as a result of ongoing transmission in Angola and the Democratic Republic of the Congo and the potential for introduction into Asia.",
  "Epidemiologist", "Ozygen Systems", "London, United Kingdom", "Feb 2016 - Mar 2016", "Hired to produce a report on numerous pathogens involved in nosocomial infection and to evaluate the applicability of ozone decontamination technology in UK healthcare settings to limit their spread."
) %>% 
  detailed_entries(company, loc, role, dates, details)
```

# Funding awards
```{r awards}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, ~ details,
  "MRC Pump Priming (£23,000)", "Imperial College London", "London, United Kingdom", "Nov 2019", "Jointly awarded £23,000 with co-PI Natsuko Imai to run a week long training workshop in Rio de Janeiro focusing on the use of mathematical models in outbreak response and policy.",
   "MRC Pump Priming (£23,000)", "Imperial College London", "London, United Kingdom", "Nov 2019", "Course was run collaboratively with the Brazilian Ministry of Health and Fundação Oswaldo Cruz (Fiocruz).",
  
  "MRC Exceptional Training Opportunity", "Imperial College London", "London, United Kingdom", "Oct 2017/Aug 2018/Jun 2019", "Oct 2017: Awarded £650 to travel to the WHO in Geneva, Switzerland to present my work on yellow fever and discuss with the yellow fever team how my PhD can provide support for their activities.",
  "MRC Exceptional Training Opportunity", "Imperial College London", "London, United Kingdom", "Oct 2017/Aug 2018/Jun 2019", "Aug 2018: Awarded £2220 to travel to Rio de Janiro and Brasilia, Brazil, and present my results on modelling yellow fever in South America at a meeting co-hosted by the Brazilian Ministry of Health and the Pan American Health Organization, as well as to set up a research collaboration with Fiocruz.",
  "MRC Exceptional Training Opportunity", "Imperial College London", "London, United Kingdom", "Oct 2017/Aug 2018/Jun 2019", "Jun 2019: Awarded £1719 to travel to Bogota, Colombia to lecture and demonstrate on a course coordinated between Imperial College London, Instituto Nacional De Salud and Pontificia Universidad Javeriana Bogota which aimed to give an introduction to infectious disease modelling."

) %>% 
  detailed_entries(company, loc, role, dates, details)
```

# Teaching
```{r teaching}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, ~ details,
  
  "Shortcourse co-organiser", "Imperial College London", "London, United Kingdom", "Jan 2021 - Sep 2021", "Co-organiser on the departments 'Mathematical modelling for the control of infectious diseases' short course, run since 1990 and designed to teach pubic health professionals about infectious disease modelling.",
  "Shortcourse co-organiser", "Imperial College London", "London, United Kingdom", "Jan 2021 - Sep 2021", "Responsible for helping redesign, and restructure, the course in order to deliver it fully online in light of the ongoing COVID-19 pandemic.",
  
  "PhD Assessor", "University of São Paulo", "São Paulo, Brazil", "Oct 2020-Jun 2023", "Examining progress and assisting with the research of a PhD student's project titled 'Spatio-temporal dynamics of yellow fever in Brazil'.",
  
  "MSc Dissertation Supervisor", "Imperial College London", "London, United Kingdom", "May 2020 - Oct 2020", "Designed and supervised MSc Epidemiology projects looking at the effect of forest fragmentation on yellow fever in Southern Brazil, and exploring the differences in transmission dynamics between yellow fever, dengue and zika.",
  
  "Graduate Teaching Assistant", "Imperial College London", "London, United Kingdom", "Jan 2017 - Jun 2022", "Teaching assistant and demonstrator for numerous modules on infectious disease modelling, statistical analysis and epidemiology.",
  
  "Shortcourse Demonstrator", "Imperial College London", "Bogota, Colombia", "Jun 2019", "Demonstrator and lecturer on a course coordinated between Imperial College London, Instituto Nacional De Salud and Pontificia Universidad Javeriana Bogota which aimed to give an introduction to infectious disease modelling.",
  
  "Shortcourse Demonstrator", "Imperial College London", "London, United Kingdom", "Sep 2017/Sep 2018/Sep 2019", "Demonstrator on numerous practical exercises and lectures on data analysis and infectious disease modelling on the aformentioned departments 'Mathematical modelling for the control of infectious diseases' short course.",
  
  "Design and implementation of an online platform for teaching infectious disease modelling", "Imperial College London", "London, United Kingdom", "Jan 2019 - Sept 2019", "Responsible for liasing between programming team and course organisers to design and translate existing practicals from Berkely Madonna to an online web interface running the Odin language.",
  "Design and implementation of an online platform for teaching infectious disease modelling", "Imperial College London", "London, United Kingdom", "Jan 2019 - Sept 2019", "Highly successful implementation with the platform now being used for both future shortcourses and the MSc Epidemiology at Imperial College London."
) %>% 
  detailed_entries(company, loc, role, dates, details)
```
  
# Presentations
```{r presentations}
tribble(
  ~ role, ~ company, ~ loc, ~ dates,
  
  "Estimating the Burden and Distribution of Long COVID in Washington State", "Western States Modeling Symposium", "Virtual", "Sep 2023",
  
      "Gastrointestinal illness among hikers on the Washington State Pacific Crest Trail, August–October 2022.", "EIS Conference 2023 and CSTE 2023", "USA", "Apr 2023",
  
    "The potential public health consequences of COVID-19 on malaria in Africa", "London Malaria Network", "London, United Kingdom", "Oct 2020",
  
    "Seasonality of agricultural exposure more important than seasonality of climate for predicting yellow fever transmission in Brazil", "American Society of Tropical Medicine and Hygiene", "National Harbor, USA", "Nov 2019",
  
    "Statistical and mathematical modelling of yellow fever in South America", "Outbreak Analysis and Modelling for Public Health", "Bogota, Colombia", "Jun 2019",

  "Land-use,  vegetation  and  habitat fragmentation  as  drivers  of  yellow  fever  transmission  in  South America", "International Conference on One Medicine One Science", "Chiang Mai, Thailand", "Feb 2019",
  
  "Yellow fever in Brazil - Modelling as a tool to inform outbreak response and public health policy", "Yellow fever forecasting: Embedding   modelling in lessons learnt exercises", "Brasilia, Brazil", "Nov 2018"
  
) %>% 
  detailed_entries(company, loc, role, dates)
```

# Publications
```{r publications_load, echo = FALSE, message = FALSE, warning = FALSE, results = FALSE}
pubs <- scholar::get_publications("xk9BhHUAAAAJ")%>%
  dplyr::mutate(author = author %>%
                  as.character,
                journal = journal %>%
                  replace(journal %in% "bioRxiv", "BioRxiv") %>%
                  replace(journal %in% "medRxiv", "MedRxiv"),
                first_author = case_when(stringr::str_starts(author, "A Hamlet|ATP Hamlet") ~ TRUE,
                                         TRUE ~ FALSE),
                preprint = case_when(journal %in% c("bioRxiv", "BioRxiv", "MedRxiv", "medRxiv", "") ~ TRUE,
                                     TRUE ~ FALSE),
                report = case_when(stringr::str_starts(title, "Report") ~ TRUE,
                                   TRUE ~ FALSE)) %>%
  dplyr::arrange(desc(year), desc(cites))

# print(pubs)

pubs <- pubs %>%
  rowwise() %>%
  mutate(
    author = case_when(
      str_ends(author, "\\.\\.\\.") ~ get_complete_authors(id = "xk9BhHUAAAAJ", pubid = pubid),
      TRUE ~ author
    )
  )


# pubs <- pubs[-which(pubs$cites == 0 & pubs$year < 2021), ]
if(any(duplicated(pubs$title))) pubs <- pubs[-which(duplicated(pubs$title)), ]
pubs <- pubs[!is.na(pubs$year), ]
pubs$author <- gsub("A Hamlet|ATP Hamlet", "\\\\textcolor{red}{\\\\textbf{A Hamlet}} ", pubs$author)

#Fix journal names
pubs <- pubs %>%
  mutate(
    journal = str_to_title(journal),
    journal = gsub("Plos", "PLoS", journal),
    journal = gsub("Bmc", "BMC", journal),
    journal = case_when(
    journal == "Bmj" ~ "BMJ",
    TRUE ~ journal
  )) %>%
  filter(!grepl("vol 6, pg e100|Imperial College", title))

name_in_first_couple <- pubs[which(pubs$first_author == F & grepl("Hamlet", pubs$author)), ]
name_in_first_couple_papers <- name_in_first_couple[which(name_in_first_couple$report == F & name_in_first_couple$preprint == F), ]

```

## First author publications - `r pubs %>% dplyr::filter(first_author == T & preprint == F) %>% nrow()`
```{r publications_first}
pubs %>%
  dplyr::filter(first_author == T & preprint == F) %>%
  dplyr::arrange(desc(year), desc(cites)) %>%
  detailed_entries(
    what = author,
    when = as.character(year),
    with = title,
    where = journal,
    .protect = F
  )
```

## Additional publications - `r name_in_first_couple_papers %>% nrow()`
```{r publications_additional}
# name_in_first_couple_papers %>%
#   # slice_head(n = 5) %>%
#   dplyr::arrange(desc(year), desc(cites)) %>%
#   detailed_entries(
#     what = title,
#     when = as.character(year),
#     with = author,
#     where = journal,
#     .protect = TRUE
#   )

pubs %>%
  dplyr::filter(!journal %in% c("doi. org/",
                                "Impact of non-pharmaceutical interventions (NPIs) to reduce COVID",
                                "Imperial College COVID", 
                                "Imperial College London",
                                "Tech. Rep. Imperial College London",
                                "Europe Pmc Free Article",
                                "Imp\\. Coll. COVID-",
                                "Imperial College COVID-") & report == F & first_author == F & preprint == F & journal != "Imperial College London") %>%
  dplyr::arrange(desc(year), desc(cites)) %>%
  detailed_entries(
    what = author,
    when = as.character(year),
    with = title,
    where = journal,
    .protect = F
  )
```